---

name: "1.$(date:yyMM)$(rev:.r)"

trigger:
- AddBuiltin-P

pool:
  vmImage: 'windows-2019'

variables:
- group: PolicyDemo

stages:
- stage: DeployAzurePolicy
  displayName: "Deploy Azure Policy to DEMO Environment"
  jobs:
  - deployment: AutomationLayerDeployment
    displayName: Deploy to CSD-Policy-Training-Sub
    pool:
      vmImage: 'windows-2019'
    environment: 'CSD-Policy-Training-Sub'
    strategy:
      runOnce:
        deploy:
          steps: 
          - download: none
          - checkout: self
            clean: 'all'
          
          - task: AzurePowerShell@4
            displayName: Deploy Policy, Create Documentation, Deploy Documentation
            inputs:
              azureSubscription: 'CSD-Policy-Training-Sub'
              ScriptType: 'FilePath'
              ScriptPath: 'Deploy.ps1'
              azurePowerShellVersion: 'LatestVersion'
              scriptArguments: >-
                -SubscriptionId '21f57d84-ca2c-4df2-8509-d4c23385675e' 
                -ParametersFile '$(Build.SourcesDirectory)\\parameters.SCGLdemo.json'  
                -DocumentationOutputDirectory '$(Build.ArtifactStagingDirectory)\\Documentation' 
                -PolicyDirectories @("$(Build.SourcesDirectory)\Policy\Security") 
                -ControlDirectories @("$(Build.SourcesDirectory)\Controls\NIST")
                -ExceptionsFile '$(Build.SourcesDirectory)\\exceptions.SCGL.json'
                -DestroyExistingAssignments 
                -Verbose
                -DocumentationAzureDevOpsOrganization "acnbootcamporg"
                -DocumentationAzureDevOpsProject "PartsUnlimited"
                -DocumentationAzureDevOpsWikiName "PartsUnlimited.wiki"
                -DocumentationPersonalAccessToken "$(DocumentationPersonalAccessToken)"
                -DocumentationScopeNickName "/PartsUnlimitedWiki/PolicyDemo"
                -PolicyExportClass "All"
                -TestingCredentialSource "PowerShell"

          
